name: flush server cache
on:
  release:
    types: [published]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Flush cache
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://desktop-updates.getplayback.com/flush?key=${{ secrets.HAZEL_API_KEY }}"
          method: "POST"
